### ISSUE TITLE
Accessing the ProcessorContext inside the transformer

### ISSUE THREAD

**Issue by smessems** [dvlopt/milena#1]
Thanks a lot for this library :)

I am setting up a transformer on the kstream. 
Inside the transformation function, I would like to issue calls to 'forward'
Can you consider attaching the context itself in -record-from-ctx - to allow interop on the **ProcessorContext** ( and avoid the need to store it again by providing :init function.

**Comment by dvlopt** [comment]
Hi,

Thanks and sorry for the delay, I have been a bit busy lately.

I will release version 1.0.0 relatively soon. The ProcessorContext will be feed to the processing function every time as an argument which is pretty much what you need.
